services:
  - type: web
    name: cinebook
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: demo
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75
