services:
  - type: web
    name: cinebook
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75
